// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Copybird) DeepCopyInto(out *Copybird) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Copybird.
func (in *Copybird) DeepCopy() *Copybird {
	if in == nil {
		return nil
	}
	out := new(Copybird)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Copybird) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopybirdList) DeepCopyInto(out *CopybirdList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Copybird, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopybirdList.
func (in *CopybirdList) DeepCopy() *CopybirdList {
	if in == nil {
		return nil
	}
	out := new(CopybirdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CopybirdList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopybirdOption) DeepCopyInto(out *CopybirdOption) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopybirdOption.
func (in *CopybirdOption) DeepCopy() *CopybirdOption {
	if in == nil {
		return nil
	}
	out := new(CopybirdOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopybirdSpec) DeepCopyInto(out *CopybirdSpec) {
	*out = *in
	in.Input.DeepCopyInto(&out.Input)
	in.Compress.DeepCopyInto(&out.Compress)
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = make([]CopybirdOption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Notifier != nil {
		in, out := &in.Notifier, &out.Notifier
		*out = make([]CopybirdOption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopybirdSpec.
func (in *CopybirdSpec) DeepCopy() *CopybirdSpec {
	if in == nil {
		return nil
	}
	out := new(CopybirdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopybirdStatus) DeepCopyInto(out *CopybirdStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopybirdStatus.
func (in *CopybirdStatus) DeepCopy() *CopybirdStatus {
	if in == nil {
		return nil
	}
	out := new(CopybirdStatus)
	in.DeepCopyInto(out)
	return out
}
